//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nes.Resources.NesResource", typeof(NesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả ngắn.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string AboutID {
            get {
                return ResourceManager.GetString("AboutID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh bìa.
        /// </summary>
        public static string AboutImages {
            get {
                return ResourceManager.GetString("AboutImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề SEO.
        /// </summary>
        public static string AboutMetaTitle {
            get {
                return ResourceManager.GetString("AboutMetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới giới thiêu.
        /// </summary>
        public static string AdminAboutCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminAboutCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa giới thiêu.
        /// </summary>
        public static string AdminAboutEditTitlePage {
            get {
                return ResourceManager.GetString("AdminAboutEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bài viết giới thiêu.
        /// </summary>
        public static string AdminAboutListTitlePage {
            get {
                return ResourceManager.GetString("AdminAboutListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới album ảnh.
        /// </summary>
        public static string AdminAlbumCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminAlbumCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa album.
        /// </summary>
        public static string AdminAlbumEditTitlePage {
            get {
                return ResourceManager.GetString("AdminAlbumEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách album ảnh.
        /// </summary>
        public static string AdminAlbumListTitlePage {
            get {
                return ResourceManager.GetString("AdminAlbumListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới danh mục.
        /// </summary>
        public static string AdminCategoryCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminCategoryCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa danh mục.
        /// </summary>
        public static string AdminCategoryEditTitlePage {
            get {
                return ResourceManager.GetString("AdminCategoryEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách danh mục.
        /// </summary>
        public static string AdminCategoryListTitlePage {
            get {
                return ResourceManager.GetString("AdminCategoryListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa bản ghi này?.
        /// </summary>
        public static string AdminConfirmDeleteMsg {
            get {
                return ResourceManager.GetString("AdminConfirmDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thông tin.
        /// </summary>
        public static string AdminContactCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminContactCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa mới thông tin.
        /// </summary>
        public static string AdminContactEditTitlePage {
            get {
                return ResourceManager.GetString("AdminContactEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách thông tin.
        /// </summary>
        public static string AdminContactListTitlePage {
            get {
                return ResourceManager.GetString("AdminContactListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bản ghi không thành công..
        /// </summary>
        public static string AdminCreateRecordFailed {
            get {
                return ResourceManager.GetString("AdminCreateRecordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bản ghi thành công..
        /// </summary>
        public static string AdminCreateRecordSuccess {
            get {
                return ResourceManager.GetString("AdminCreateRecordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi không thành công. Vui lòng thử lần sau..
        /// </summary>
        public static string AdminDeleteRecordFailed {
            get {
                return ResourceManager.GetString("AdminDeleteRecordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi thành công..
        /// </summary>
        public static string AdminDeleteRecordSuccess {
            get {
                return ResourceManager.GetString("AdminDeleteRecordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin nhóm menu.
        /// </summary>
        public static string AdminEditMenuTypeTitlePage {
            get {
                return ResourceManager.GetString("AdminEditMenuTypeTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bản ghi không thành công..
        /// </summary>
        public static string AdminEditRecordFailed {
            get {
                return ResourceManager.GetString("AdminEditRecordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bản ghi thành công..
        /// </summary>
        public static string AdminEditRecordSucess {
            get {
                return ResourceManager.GetString("AdminEditRecordSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm menu.
        /// </summary>
        public static string AdminEmptyGroupSelectionText {
            get {
                return ResourceManager.GetString("AdminEmptyGroupSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chủ đề cha.
        /// </summary>
        public static string AdminEmptySelectionTextForFunction {
            get {
                return ResourceManager.GetString("AdminEmptySelectionTextForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết phản hồi.
        /// </summary>
        public static string AdminFeedbackDetailTitlePage {
            get {
                return ResourceManager.GetString("AdminFeedbackDetailTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phản hồi.
        /// </summary>
        public static string AdminFeedbackListTitlePage {
            get {
                return ResourceManager.GetString("AdminFeedbackListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới footer.
        /// </summary>
        public static string AdminFooterCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminFooterCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa footer.
        /// </summary>
        public static string AdminFooterEditTitlePage {
            get {
                return ResourceManager.GetString("AdminFooterEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách footer.
        /// </summary>
        public static string AdminFooterListTitlePage {
            get {
                return ResourceManager.GetString("AdminFooterListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string AdminFunctionActionColumnHeaderText {
            get {
                return ResourceManager.GetString("AdminFunctionActionColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string AdminFunctionCreateButtonText {
            get {
                return ResourceManager.GetString("AdminFunctionCreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới chức năng.
        /// </summary>
        public static string AdminFunctionCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminFunctionCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string AdminFunctionDeleteButtonText {
            get {
                return ResourceManager.GetString("AdminFunctionDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string AdminFunctionEditButtonText {
            get {
                return ResourceManager.GetString("AdminFunctionEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa chức năng.
        /// </summary>
        public static string AdminFunctionEditTitlePage {
            get {
                return ResourceManager.GetString("AdminFunctionEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chức năng không hơp lê.
        /// </summary>
        public static string AdminFunctionIdRegexMsg {
            get {
                return ResourceManager.GetString("AdminFunctionIdRegexMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chức năng.
        /// </summary>
        public static string AdminFunctionListTitlePage {
            get {
                return ResourceManager.GetString("AdminFunctionListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string AdminFunctionUpdateButtonText {
            get {
                return ResourceManager.GetString("AdminFunctionUpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string AdminFunctionViewButtonText {
            get {
                return ResourceManager.GetString("AdminFunctionViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhóm slide.
        /// </summary>
        public static string AdminGroupSlideCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminGroupSlideCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa nhóm slide.
        /// </summary>
        public static string AdminGroupSlideEditTitlePage {
            get {
                return ResourceManager.GetString("AdminGroupSlideEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhóm Slide.
        /// </summary>
        public static string AdminGroupSlideListTitlePage {
            get {
                return ResourceManager.GetString("AdminGroupSlideListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string AdminHomeMenuText {
            get {
                return ResourceManager.GetString("AdminHomeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string AdminHomePageTitleText {
            get {
                return ResourceManager.GetString("AdminHomePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm....
        /// </summary>
        public static string AdminHomeSearchText {
            get {
                return ResourceManager.GetString("AdminHomeSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu chưa đúng yêu cầu..
        /// </summary>
        public static string AdminInserRecordInvalid {
            get {
                return ResourceManager.GetString("AdminInserRecordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bản ghi thành công. .
        /// </summary>
        public static string AdminInserRecordSuccess {
            get {
                return ResourceManager.GetString("AdminInserRecordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới ngôn ngữ.
        /// </summary>
        public static string AdminLanguageCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminLanguageCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa ngôn ngữ.
        /// </summary>
        public static string AdminLanguageEditTitlePage {
            get {
                return ResourceManager.GetString("AdminLanguageEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách ngôn ngữ.
        /// </summary>
        public static string AdminLanguageListTitlePage {
            get {
                return ResourceManager.GetString("AdminLanguageListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string AdminLoginButtonText {
            get {
                return ResourceManager.GetString("AdminLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập hệ thống.
        /// </summary>
        public static string AdminLoginHeaderText {
            get {
                return ResourceManager.GetString("AdminLoginHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng..
        /// </summary>
        public static string AdminLoginMessageError {
            get {
                return ResourceManager.GetString("AdminLoginMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string AdminLoginPasswordText {
            get {
                return ResourceManager.GetString("AdminLoginPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhớ mật khẩu?.
        /// </summary>
        public static string AdminLoginRemembermeText {
            get {
                return ResourceManager.GetString("AdminLoginRemembermeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string AdminLoginUsernameText {
            get {
                return ResourceManager.GetString("AdminLoginUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string AdminMasterLogoutText {
            get {
                return ResourceManager.GetString("AdminMasterLogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới menu.
        /// </summary>
        public static string AdminMenuCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminMenuCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin menu.
        /// </summary>
        public static string AdminMenuEditTitlePage {
            get {
                return ResourceManager.GetString("AdminMenuEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách menu.
        /// </summary>
        public static string AdminMenuListTitlePage {
            get {
                return ResourceManager.GetString("AdminMenuListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới loại Menu.
        /// </summary>
        public static string AdminMenuTypeCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminMenuTypeCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin loại Menu.
        /// </summary>
        public static string AdminMenuTypeEditTitlePage {
            get {
                return ResourceManager.GetString("AdminMenuTypeEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm menu.
        /// </summary>
        public static string AdminMenuTypeListTitlePage {
            get {
                return ResourceManager.GetString("AdminMenuTypeListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tin tức.
        /// </summary>
        public static string AdminNewsCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminNewsCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa tin tức.
        /// </summary>
        public static string AdminNewsEditTitlePage {
            get {
                return ResourceManager.GetString("AdminNewsEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tin tức.
        /// </summary>
        public static string AdminNewsListTitlePage {
            get {
                return ResourceManager.GetString("AdminNewsListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát hành.
        /// </summary>
        public static string AdminNewsPublishedStatusText {
            get {
                return ResourceManager.GetString("AdminNewsPublishedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa phát hành.
        /// </summary>
        public static string AdminNewsUnPublishedStatusText {
            get {
                return ResourceManager.GetString("AdminNewsUnPublishedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào trong danh sách..
        /// </summary>
        public static string AdminNoRecordMessage {
            get {
                return ResourceManager.GetString("AdminNoRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập đầy đủ các trường bắt buộc dưới đây..
        /// </summary>
        public static string AdminNoteForm {
            get {
                return ResourceManager.GetString("AdminNoteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string AdminNoteFormEmpty {
            get {
                return ResourceManager.GetString("AdminNoteFormEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở trong cửa sổ mới.
        /// </summary>
        public static string AdminOpenNewWindowText {
            get {
                return ResourceManager.GetString("AdminOpenNewWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở trong cửa sổ chính.
        /// </summary>
        public static string AdminOpenSameWindowText {
            get {
                return ResourceManager.GetString("AdminOpenSameWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        public static string AdminPermissionDiviButtonText {
            get {
                return ResourceManager.GetString("AdminPermissionDiviButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền cho nhóm: .
        /// </summary>
        public static string AdminPermistionDiviTitlePage {
            get {
                return ResourceManager.GetString("AdminPermistionDiviTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm ảnh mới.
        /// </summary>
        public static string AdminPhotoCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminPhotoCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa hình ảnh.
        /// </summary>
        public static string AdminPhotoEditTitlePage {
            get {
                return ResourceManager.GetString("AdminPhotoEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hình ảnh.
        /// </summary>
        public static string AdminPhotoListTitlePage {
            get {
                return ResourceManager.GetString("AdminPhotoListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới danh mục sản phẩm.
        /// </summary>
        public static string AdminProductCategoryCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminProductCategoryCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa danh mục sản phẩm.
        /// </summary>
        public static string AdminProductCategoryEditTitlePage {
            get {
                return ResourceManager.GetString("AdminProductCategoryEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string AdminProductCategoryListTitlePage {
            get {
                return ResourceManager.GetString("AdminProductCategoryListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới quyền.
        /// </summary>
        public static string AdminRoleCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminRoleCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quyền.
        /// </summary>
        public static string AdminRoleListTitlePage {
            get {
                return ResourceManager.GetString("AdminRoleListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin quyền.
        /// </summary>
        public static string AdminRoleTitlePage {
            get {
                return ResourceManager.GetString("AdminRoleTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lại.
        /// </summary>
        public static string AdminSaveButtonText {
            get {
                return ResourceManager.GetString("AdminSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ảnh.
        /// </summary>
        public static string AdminSelectImageButtonText {
            get {
                return ResourceManager.GetString("AdminSelectImageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới slide.
        /// </summary>
        public static string AdminSlideCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminSlideCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa slide.
        /// </summary>
        public static string AdminSlideEditTitlePage {
            get {
                return ResourceManager.GetString("AdminSlideEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách slide.
        /// </summary>
        public static string AdminSlideListTitlePage {
            get {
                return ResourceManager.GetString("AdminSlideListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới người dùng.
        /// </summary>
        public static string AdminUserCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminUserCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới nhóm người dùng.
        /// </summary>
        public static string AdminUserGroupCreateTitlePage {
            get {
                return ResourceManager.GetString("AdminUserGroupCreateTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin nhóm người dùng.
        /// </summary>
        public static string AdminUserGroupEditTitlePage {
            get {
                return ResourceManager.GetString("AdminUserGroupEditTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm người dùng.
        /// </summary>
        public static string AdminUserGroupListTitlePage {
            get {
                return ResourceManager.GetString("AdminUserGroupListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài khoản.
        /// </summary>
        public static string AdminUserListTitlePage {
            get {
                return ResourceManager.GetString("AdminUserListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string AlbumCreatedBy {
            get {
                return ResourceManager.GetString("AlbumCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string AlbumCreatedDate {
            get {
                return ResourceManager.GetString("AlbumCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string AlbumDescription {
            get {
                return ResourceManager.GetString("AlbumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã album.
        /// </summary>
        public static string AlbumID {
            get {
                return ResourceManager.GetString("AlbumID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh bìa.
        /// </summary>
        public static string AlbumImages {
            get {
                return ResourceManager.GetString("AlbumImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string AlbumLanguageCode {
            get {
                return ResourceManager.GetString("AlbumLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta description.
        /// </summary>
        public static string AlbumMetaDescription {
            get {
                return ResourceManager.GetString("AlbumMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta keywords.
        /// </summary>
        public static string AlbumMetaKeywords {
            get {
                return ResourceManager.GetString("AlbumMetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string AlbumName {
            get {
                return ResourceManager.GetString("AlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tiêu đề.
        /// </summary>
        public static string AlbumNameRequired {
            get {
                return ResourceManager.GetString("AlbumNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tư.
        /// </summary>
        public static string AlbumOrder {
            get {
                return ResourceManager.GetString("AlbumOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string AlbumStatus {
            get {
                return ResourceManager.GetString("AlbumStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string CategoryCreatedBy {
            get {
                return ResourceManager.GetString("CategoryCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CategoryCreatedDate {
            get {
                return ResourceManager.GetString("CategoryCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string CategoryDescription {
            get {
                return ResourceManager.GetString("CategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string CategoryImages {
            get {
                return ResourceManager.GetString("CategoryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh muc giới thiêu.
        /// </summary>
        public static string CategoryIsIntroduced {
            get {
                return ResourceManager.GetString("CategoryIsIntroduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string CategoryLanguageCode {
            get {
                return ResourceManager.GetString("CategoryLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        public static string CategoryMetaDescription {
            get {
                return ResourceManager.GetString("CategoryMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords.
        /// </summary>
        public static string CategoryMetaKeywords {
            get {
                return ResourceManager.GetString("CategoryMetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta title.
        /// </summary>
        public static string CategoryMetaTitle {
            get {
                return ResourceManager.GetString("CategoryMetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ký tư không đươc vươt quá 250.
        /// </summary>
        public static string CategoryNameLong {
            get {
                return ResourceManager.GetString("CategoryNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhâp tên.
        /// </summary>
        public static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        public static string CategoryOrder {
            get {
                return ResourceManager.GetString("CategoryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục cha.
        /// </summary>
        public static string CategoryParentID {
            get {
                return ResourceManager.GetString("CategoryParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string CategoryStatus {
            get {
                return ResourceManager.GetString("CategoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string ConfigItemDescription {
            get {
                return ResourceManager.GetString("ConfigItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cấu hình.
        /// </summary>
        public static string ConfigItemName {
            get {
                return ResourceManager.GetString("ConfigItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài nhãn là 50.
        /// </summary>
        public static string ConfigItemNameLong {
            get {
                return ResourceManager.GetString("ConfigItemNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tên.
        /// </summary>
        public static string ConfigItemNameRequired {
            get {
                return ResourceManager.GetString("ConfigItemNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key duy nhất.
        /// </summary>
        public static string ConfigItemUniqueKey {
            get {
                return ResourceManager.GetString("ConfigItemUniqueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập key.
        /// </summary>
        public static string ConfigItemUniqueKeyRequired {
            get {
                return ResourceManager.GetString("ConfigItemUniqueKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài giá trị là 50 ký tự.
        /// </summary>
        public static string ConfigItemUnitLong {
            get {
                return ResourceManager.GetString("ConfigItemUnitLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập đơn vị.
        /// </summary>
        public static string ConfigItemUnitRequired {
            get {
                return ResourceManager.GetString("ConfigItemUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài giá trị là 250 ký tự.
        /// </summary>
        public static string ConfigItemValueLong {
            get {
                return ResourceManager.GetString("ConfigItemValueLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập giá trị.
        /// </summary>
        public static string ConfigItemValueRequired {
            get {
                return ResourceManager.GetString("ConfigItemValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key chỉ được dài 50 ký tự.
        /// </summary>
        public static string ConfigUniqueKeyLong {
            get {
                return ResourceManager.GetString("ConfigUniqueKeyLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string ContactContent {
            get {
                return ResourceManager.GetString("ContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thông tin.
        /// </summary>
        public static string ContactID {
            get {
                return ResourceManager.GetString("ContactID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string ContactLanguageCode {
            get {
                return ResourceManager.GetString("ContactLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string ContactStatus {
            get {
                return ResourceManager.GetString("ContactStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhâp tiêu đề.
        /// </summary>
        public static string ContactTitleRequired {
            get {
                return ResourceManager.GetString("ContactTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập email.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm mới dữ liệu. Vui lòng thử lại hoặc liên hệ với quản trị viên..
        /// </summary>
        public static string ErrorCreateRecordMessage {
            get {
                return ResourceManager.GetString("ErrorCreateRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống số về sự cố như sau:.
        /// </summary>
        public static string ErrorDetailText {
            get {
                return ResourceManager.GetString("ErrorDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bản ghi nào trong cơ sở dữ liệu..
        /// </summary>
        public static string ErrorGetRecordMessage {
            get {
                return ResourceManager.GetString("ErrorGetRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung tâm thông báo sự cố.
        /// </summary>
        public static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin trên form chưa đúng..
        /// </summary>
        public static string ErrorValidForm {
            get {
                return ResourceManager.GetString("ErrorValidForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string FeedbackAddress {
            get {
                return ResourceManager.GetString("FeedbackAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string FeedbackCompany {
            get {
                return ResourceManager.GetString("FeedbackCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string FeedbackCreatedDate {
            get {
                return ResourceManager.GetString("FeedbackCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hòm thư.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string FeedbackID {
            get {
                return ResourceManager.GetString("FeedbackID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xem.
        /// </summary>
        public static string FeedbackIsReaded {
            get {
                return ResourceManager.GetString("FeedbackIsReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string FeedbackMessage {
            get {
                return ResourceManager.GetString("FeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đầy đủ.
        /// </summary>
        public static string FeedbackName {
            get {
                return ResourceManager.GetString("FeedbackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string FeedbackPhone {
            get {
                return ResourceManager.GetString("FeedbackPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string FooterContent {
            get {
                return ResourceManager.GetString("FooterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string FooterID {
            get {
                return ResourceManager.GetString("FooterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string FooterLanguageCode {
            get {
                return ResourceManager.GetString("FooterLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string FooterStatus {
            get {
                return ResourceManager.GetString("FooterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string FooterTitle {
            get {
                return ResourceManager.GetString("FooterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập tên của footer.
        /// </summary>
        public static string FooterTitleRequired {
            get {
                return ResourceManager.GetString("FooterTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập họ tên.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string FunctionCreatedDate {
            get {
                return ResourceManager.GetString("FunctionCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Class.
        /// </summary>
        public static string FunctionCssClass {
            get {
                return ResourceManager.GetString("FunctionCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string FunctionDescription {
            get {
                return ResourceManager.GetString("FunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài cho phép là 50.
        /// </summary>
        public static string FunctionDescriptionLong {
            get {
                return ResourceManager.GetString("FunctionDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập mô tả.
        /// </summary>
        public static string FunctionDescriptionRequired {
            get {
                return ResourceManager.GetString("FunctionDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chức năng.
        /// </summary>
        public static string FunctionID {
            get {
                return ResourceManager.GetString("FunctionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string FunctionLock {
            get {
                return ResourceManager.GetString("FunctionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức năng.
        /// </summary>
        public static string FunctionName {
            get {
                return ResourceManager.GetString("FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài cho phép là 50.
        /// </summary>
        public static string FunctionNameLong {
            get {
                return ResourceManager.GetString("FunctionNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập tên chức năng.
        /// </summary>
        public static string FunctionNameRequired {
            get {
                return ResourceManager.GetString("FunctionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string FunctionOrder {
            get {
                return ResourceManager.GetString("FunctionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập thứ tự.
        /// </summary>
        public static string FunctionOrderRequired {
            get {
                return ResourceManager.GetString("FunctionOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu cha.
        /// </summary>
        public static string FunctionParentIDName {
            get {
                return ResourceManager.GetString("FunctionParentIDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        public static string FunctionUrl {
            get {
                return ResourceManager.GetString("FunctionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập đường dẫn.
        /// </summary>
        public static string FunctionUrlRequired {
            get {
                return ResourceManager.GetString("FunctionUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về trang danh sách.
        /// </summary>
        public static string GoBackToListText {
            get {
                return ResourceManager.GetString("GoBackToListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặc định.
        /// </summary>
        public static string LanguageIsDefault {
            get {
                return ResourceManager.GetString("LanguageIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngôn ngữ.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài cho phép là 50.
        /// </summary>
        public static string LanguageNameLong {
            get {
                return ResourceManager.GetString("LanguageNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tên ngôn ngữ.
        /// </summary>
        public static string LanguageNameRequired {
            get {
                return ResourceManager.GetString("LanguageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string LanguageStatus {
            get {
                return ResourceManager.GetString("LanguageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiển thị.
        /// </summary>
        public static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài nhãn là 250.
        /// </summary>
        public static string LinkTextLong {
            get {
                return ResourceManager.GetString("LinkTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiển thị là bắt buộc.
        /// </summary>
        public static string LinkTextRequired {
            get {
                return ResourceManager.GetString("LinkTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string MenuCreatedDate {
            get {
                return ResourceManager.GetString("MenuCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        public static string MenuCssClass {
            get {
                return ResourceManager.GetString("MenuCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string MenuDescription {
            get {
                return ResourceManager.GetString("MenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string MenuGroupID {
            get {
                return ResourceManager.GetString("MenuGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã menu.
        /// </summary>
        public static string MenuID {
            get {
                return ResourceManager.GetString("MenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        public static string MenuLock {
            get {
                return ResourceManager.GetString("MenuLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên menu.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tên menu quá giới han.
        /// </summary>
        public static string MenuNameLong {
            get {
                return ResourceManager.GetString("MenuNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhâp tên menu.
        /// </summary>
        public static string MenuNameRequired {
            get {
                return ResourceManager.GetString("MenuNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        public static string MenuOrder {
            get {
                return ResourceManager.GetString("MenuOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhâp sắp xếp.
        /// </summary>
        public static string MenuOrderRequired {
            get {
                return ResourceManager.GetString("MenuOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu cha.
        /// </summary>
        public static string MenuParentIDName {
            get {
                return ResourceManager.GetString("MenuParentIDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string MenuTypeCreateBy {
            get {
                return ResourceManager.GetString("MenuTypeCreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string MenuTypeCreateDate {
            get {
                return ResourceManager.GetString("MenuTypeCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string MenuTypeDescription {
            get {
                return ResourceManager.GetString("MenuTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm.
        /// </summary>
        public static string MenuTypeId {
            get {
                return ResourceManager.GetString("MenuTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        public static string MenuTypeName {
            get {
                return ResourceManager.GetString("MenuTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm giới hạn 250 ký tự.
        /// </summary>
        public static string MenuTypeNameLong {
            get {
                return ResourceManager.GetString("MenuTypeNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tên nhóm.
        /// </summary>
        public static string MenuTypeNameRequired {
            get {
                return ResourceManager.GetString("MenuTypeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string MenuTypeStatus {
            get {
                return ResourceManager.GetString("MenuTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string MenuTypeUpdatedBy {
            get {
                return ResourceManager.GetString("MenuTypeUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string MenuTypeUpdatedDate {
            get {
                return ResourceManager.GetString("MenuTypeUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        public static string MenuUrl {
            get {
                return ResourceManager.GetString("MenuUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn bắt buôc.
        /// </summary>
        public static string MenuUrlRequired {
            get {
                return ResourceManager.GetString("MenuUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập số điện thoại.
        /// </summary>
        public static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string NewsCategoryID {
            get {
                return ResourceManager.GetString("NewsCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string NewsContent {
            get {
                return ResourceManager.GetString("NewsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string NewsDescription {
            get {
                return ResourceManager.GetString("NewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string NewsID {
            get {
                return ResourceManager.GetString("NewsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string NewsImages {
            get {
                return ResourceManager.GetString("NewsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string NewsLanguageCode {
            get {
                return ResourceManager.GetString("NewsLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta title.
        /// </summary>
        public static string NewsMetaTitle {
            get {
                return ResourceManager.GetString("NewsMetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phát hành.
        /// </summary>
        public static string NewsPublishedDate {
            get {
                return ResourceManager.GetString("NewsPublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin liên quan.
        /// </summary>
        public static string NewsRelatedNewses {
            get {
                return ResourceManager.GetString("NewsRelatedNewses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguồn.
        /// </summary>
        public static string NewsSource {
            get {
                return ResourceManager.GetString("NewsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tối đa cho phép là 250 ký tự.
        /// </summary>
        public static string NewsTitleLong {
            get {
                return ResourceManager.GetString("NewsTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tiêu đề.
        /// </summary>
        public static string NewsTitleRequired {
            get {
                return ResourceManager.GetString("NewsTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin hot.
        /// </summary>
        public static string NewsUpTopHot {
            get {
                return ResourceManager.GetString("NewsUpTopHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới.
        /// </summary>
        public static string NewsUpTopNew {
            get {
                return ResourceManager.GetString("NewsUpTopNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần xem.
        /// </summary>
        public static string NewsViewCount {
            get {
                return ResourceManager.GetString("NewsViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có sự cho phép cần thiết để thực hiện hành động này.
        /// </summary>
        public static string NotPermissionMessage {
            get {
                return ResourceManager.GetString("NotPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tối thiểu của mật khẩu là 6 ký tự.
        /// </summary>
        public static string PasswordMinLong {
            get {
                return ResourceManager.GetString("PasswordMinLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập mật khẩu.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string PermissionFunctionId {
            get {
                return ResourceManager.GetString("PermissionFunctionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền cho phép.
        /// </summary>
        public static string PermissionRoleId {
            get {
                return ResourceManager.GetString("PermissionRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã album.
        /// </summary>
        public static string PhotoAlbumID {
            get {
                return ResourceManager.GetString("PhotoAlbumID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string PhotoCreatedBy {
            get {
                return ResourceManager.GetString("PhotoCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string PhotoCreatedDate {
            get {
                return ResourceManager.GetString("PhotoCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string PhotoDescription {
            get {
                return ResourceManager.GetString("PhotoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PhotoID {
            get {
                return ResourceManager.GetString("PhotoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string PhotoImages {
            get {
                return ResourceManager.GetString("PhotoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ảnh.
        /// </summary>
        public static string PhotoName {
            get {
                return ResourceManager.GetString("PhotoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string PhotoStatus {
            get {
                return ResourceManager.GetString("PhotoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string ProductCategoryID {
            get {
                return ResourceManager.GetString("ProductCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string ProductCreatedBy {
            get {
                return ResourceManager.GetString("ProductCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string ProductCreatedDate {
            get {
                return ResourceManager.GetString("ProductCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết sản phẩm.
        /// </summary>
        public static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string ProductImages {
            get {
                return ResourceManager.GetString("ProductImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string ProductLanguageCode {
            get {
                return ResourceManager.GetString("ProductLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta descriptions.
        /// </summary>
        public static string ProductMetaDescription {
            get {
                return ResourceManager.GetString("ProductMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta keywords.
        /// </summary>
        public static string ProductMetaKeywords {
            get {
                return ResourceManager.GetString("ProductMetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string ProductStatus {
            get {
                return ResourceManager.GetString("ProductStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề quá dài hơn 250 ký tư.
        /// </summary>
        public static string ProductTitleLong {
            get {
                return ResourceManager.GetString("ProductTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu điền tiêu đề.
        /// </summary>
        public static string ProductTitleRequired {
            get {
                return ResourceManager.GetString("ProductTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm hot.
        /// </summary>
        public static string ProductUpTopHot {
            get {
                return ResourceManager.GetString("ProductUpTopHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        public static string ProductUpTopNew {
            get {
                return ResourceManager.GetString("ProductUpTopNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượt xem.
        /// </summary>
        public static string ProductViewCount {
            get {
                return ResourceManager.GetString("ProductViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string RoleCreateBy {
            get {
                return ResourceManager.GetString("RoleCreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string RoleCreateDate {
            get {
                return ResourceManager.GetString("RoleCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string RoleDescription {
            get {
                return ResourceManager.GetString("RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quyền.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài nhãn là 250.
        /// </summary>
        public static string RoleNameLong {
            get {
                return ResourceManager.GetString("RoleNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tên.
        /// </summary>
        public static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string RoleStatus {
            get {
                return ResourceManager.GetString("RoleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string RoleUpdatedBy {
            get {
                return ResourceManager.GetString("RoleUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string RoleUpdatedDate {
            get {
                return ResourceManager.GetString("RoleUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string UserCreatedBy {
            get {
                return ResourceManager.GetString("UserCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string UserCreatedDate {
            get {
                return ResourceManager.GetString("UserCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string UserGroupCreatedDate {
            get {
                return ResourceManager.GetString("UserGroupCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string UserGroupDescription {
            get {
                return ResourceManager.GetString("UserGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        public static string UserGroupName {
            get {
                return ResourceManager.GetString("UserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm giới hạn 50 ký tự.
        /// </summary>
        public static string UserGroupNameLong {
            get {
                return ResourceManager.GetString("UserGroupNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập tên nhóm.
        /// </summary>
        public static string UserGroupNameRequired {
            get {
                return ResourceManager.GetString("UserGroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string UserGroupStatus {
            get {
                return ResourceManager.GetString("UserGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tối đa là 20 ký tự.
        /// </summary>
        public static string UserNameLong {
            get {
                return ResourceManager.GetString("UserNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tài khoản.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cấp 2.
        /// </summary>
        public static string UserPasswordLevel2 {
            get {
                return ResourceManager.GetString("UserPasswordLevel2", resourceCulture);
            }
        }
    }
}
