//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nes.Dal.EntityModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Permissions")]
    public partial class Permission
    {
        [Key]
        public int ID { get; set; }
        public string GroupID { get; set; }
         [Display(Name = "PermissionRoleId", ResourceType = typeof(Resources.NesResource))]
        public string RoleID { get; set; }
        [Display(Name = "PermissionFunctionId", ResourceType = typeof(Resources.NesResource))]
        public string FunctionID { get; set; }

        public virtual UserGroup UserGroup { set; get; }
        public virtual Role Role { set; get; }
        public virtual Function Function { set; get; }
    }
}
