//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nes.Dal.EntityModels
{
    using Nes.Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Roles")]
    public partial class Role
    {
        [Key]
        public string ID { get; set; }
        [Required(ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "RoleNameRequired")]
        [StringLength(50, ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "RoleNameLong")]
        [Display(Name = "RoleName", ResourceType = typeof(Resources.NesResource))]
        public string Name { get; set; }
        [Display(Name = "RoleDescription", ResourceType = typeof(Resources.NesResource))]
        public string Description { get; set; }
          [Display(Name = "RoleCreateDate", ResourceType = typeof(Resources.NesResource))]
        public System.DateTime CreatedDate { get; set; }
         [Display(Name = "RoleCreateBy", ResourceType = typeof(Resources.NesResource))]
        public string CreatedBy { get; set; }
         [Display(Name = "RoleUpdatedDate", ResourceType = typeof(Resources.NesResource))]
        public Nullable<System.DateTime> UpdatedDate { get; set; }
         [Display(Name = "RoleUpdatedBy", ResourceType = typeof(Resources.NesResource))]
        public string UpdatedBy { get; set; }
         [Display(Name = "RoleStatus", ResourceType = typeof(Resources.NesResource))]
        public bool IsActived { get; set; }
        public bool IsDeleted { get; set; }
    }
}
