//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nes.Dal.EntityModels
{
    using Nes.Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SystemConfigs")]
    public partial class SystemConfig
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "ConfigItemNameRequired")]
        [StringLength(50, ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "ConfigItemNameLong")]
        [Display(Name = "ConfigItemName", ResourceType = typeof(Resources.NesResource))]
        public string Name { get; set; }

        [Required(ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "ConfigItemUniqueKeyRequired")]
        [StringLength(50, ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "ConfigUniqueKeyLong")]
        [Display(Name = "ConfigItemUniqueKey", ResourceType = typeof(Resources.NesResource))]
        public string UniqueKey { get; set; }

        [Required(ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "ConfigItemValueRequired")]
        [StringLength(50, ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "ConfigItemValueLong")]
        [Display(Name = "ConfigItemValue", ResourceType = typeof(Resources.NesResource))]
        public string Value { get; set; }

        [Required(ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "ConfigItemUnitRequired")]
        [StringLength(50, ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "ConfigItemUnitLong")]
        [Display(Name = "ConfigItemUnit", ResourceType = typeof(Resources.NesResource))]
        public string Unit { get; set; }

        [Display(Name = "ConfigItemDescription", ResourceType = typeof(Resources.NesResource))]
        public string Description { get; set; }
        [Required]
        public System.DateTime CreatedDate { get; set; }
        [Required]
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        [Required]
        public bool IsDeleted { get; set; }
    }
}
