//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nes.Dal.EntityModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

     [Table("UserActivityLogs")]
    public partial class UserActivityLog
    {
        [Key]
        public int ID { get; set; }
        public string ActionName { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string IPAddress { get; set; }
        public string SessionID { get; set; }
        public string UserName { get; set; }

        public virtual User User { set; get; }
    }
}
