//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nes.Dal.EntityModels
{
    using Nes.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

     [Table("UserGroups")]
    public partial class UserGroup
    {
        [Key]
        public string ID { get; set; }
        [Required(ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "UserGroupNameRequired")]
        [StringLength(50, ErrorMessageResourceType = typeof(NesResource), ErrorMessageResourceName = "UserGroupNameLong")]
        [Display(Name = "UserGroupName", ResourceType = typeof(Resources.NesResource))]
        public string Name { get; set; }
        [Display(Name = "UserGroupDescription", ResourceType = typeof(Resources.NesResource))]
        public string Description { get; set; }
          [Display(Name = "UserGroupCreatedDate", ResourceType = typeof(Resources.NesResource))]
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        [Display(Name = "UserGroupStatus", ResourceType = typeof(Resources.NesResource))]
        public bool IsActived { get; set; }
        public bool IsDeleted { get; set; }

    }
}
